### PR TITLE
Fix for #48

### PR DESCRIPTION
**Pull request by greecemunky**
Changed default sanitizeStr function to not trim.
Added secondary sanitizeStrTrim function to perform the trim.
Renamed most calls to sanitizeStr with sanitizeStrTrim, excluding those possibly required to retain spaces (some may still need to be changed, or changed back).
Display of directories/links/files set to have spaces shown.

### CODE REVIEW

**Comment by MonstaApps** [comment]
You applied the changes to an older version of index.php. I've manually incorporated the changes into the current version.

**Comment by greecemunky** [comment]
Sorry about that, I'm pretty much new to Git and GitHub.
It looks like there's now two branches, master and issue-48?
Based on modification dates, I'm not sure changes made their way into master.

**Comment by MonstaApps** [comment]
Yes I manually pulled all the changes into the master. I've deleted the second branch.

**Comment by greecemunky** [comment]
I still can't see the changes in this index.php so I may try to rebase my local branch and generate a new pull request based on this current index.php.

**Comment by MonstaApps** [comment]
Whoops sorry, I haven't uploaded 1.6.4 to Github. Will do it now.

**Pull request closed without merging**
