### PR TITLE
Fix broken downloads

### LINKED ISSUE #66: Downloads are broken because there is additional HTML appended to each file
This happens when downloading single files and also if multiple files are downloaded (then the zip has data appended). See:
```
$ tail monstabox_2016_03_17_12_01_40.zip 
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<script type="text/javascript">
    parent.processForm('&ftpAction=openFolder');
</script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by herndlm**
This fixes #66

### CODE REVIEW

**Comment by MonstaApps** [comment]
I'm not aware of this being an issue. I tested it myself but couldn't replicate the problem. I'd be interested to hear if anyone else has experienced this.

**Comment by ggeorgg** [comment]
I can't replicate this problem either. Just downloaded some files as zip and could open then as expected. I don't know how to reproduce this problem.

**Comment by greecemunky** [comment]
This appears to occur when a web browser (in this situation, the OP's web browser) does not respect the Content-Length response header when downloading files.

As a test, in Monsta I adjusted the Content-Length value by doing **(filesize($fp1)/2)**, then downloaded a file.  In both Firefox 44.0 and IE 11, the resulting downloaded file's size was half of the file, which means both of those web browsers respect the Content-Length header (i.e. not storing more bytes than the value specified) and as such the downloaded file is incomplete.

From what I can see with using Wireshark (as web browser developer tools don't always capture and display all), both web browsers keep requesting packets until the number of bytes specified by the Content-Length header is met, but not strictly.  When downloading a file whose Content-Length is **filesize($fp1)**, I can see the additional HTML data that the OP is seeing in the downloaded file (the output from **parentOpenFolder()**) in the TCP packet, however Firefox and IE are not storing this as part of the file.  I also don't know whether they are actually rendering it, or silently discarding it.

When downloading a file whose Content-Length is **(filesize($fp1)/2)**, not all content is received therefore not stored in the downloaded file.  It appears for these web browsers, after the packet is received, it checks whether the number of bytes received is greater than or equal to the Content-Length header's value, and if it is it stops receiving additional data.  This is based on receiving much less data in this request, and not receiving the additional HTML data from **parentOpenFolder()**, due to the lesser Content-Length value.

To properly support web browsers that do not respect the Content-Length header, I suggest accepting the pull request, as I don't think the call to **parentOpenFolder()** after downloading a file/s, and possibly after uploading, is accepted by the browser (for the same reason - the client browser stops storing excess bytes, which is what the content of **parentOpenFolder()** would be seen as).

**Comment by MonstaApps** [comment]
Thanks very much for investigating this. I tried the code with the parent call commented out and nothing seemed to break, so I'm having trouble remembering why it was in there in the first place. I think it was to avoid a blank screen after the download has started, but that seems redundant.

**Comment by greecemunky** [comment]
The one thing I did not test is file uploads.  Maybe that code was implemented to refresh the page after a file was uploaded, but was added to both upload and download actions.

I won't be able to test this until tonight.

**Comment by MonstaApps** [comment]
The iFrame upload was just for old IE browsers that didn't support something the new browsers do (I forget.) I'm happy to let support for IE lapse.

**Comment by greecemunky** [comment]
Ahh, no worries!

**Comment by herndlm** [comment]
@greecemunky Also thank you from me for digging into this and explaining the interesting details. I was using Chromium 49 btw

**Comment by greecemunky** [comment]
@monojp No worries mate. However, for my own curiosity I tested Chromium Portable 49.0.2587.3 (on Windows 7) but failed to replicate your issues.  My test downloads (zip files) came through successfully as they did in Firefox and IE.

Could your web server or its PHP not be honouring, or even removing, the Content-Length header added by Monsta?  Or could your browser (maybe an add-in / extension is contributing)?

You could test both former and newest versions on Monsta, noting the response headers via the web browser's developer tools.  Trying another web browser will potentially isolate the issue to your Chromium.

**Comment by herndlm** [comment]
Yeah you're right, looks like it's coming from the webserver or PHP. I don't see the header at all in my chrome or firefox and the appended data happens on both of them with the old version.

Detailed headers:

```
Request URL:<url monstaftp>/?dl=~%2Ffoo.txt
Request Method:GET
Status Code:200 OK
Remote Address:<server ip>:443

Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Description:File Transfer
Content-Disposition:attachment; filename="foo.txt"
Content-Encoding:gzip
Content-Transfer-Encoding:Binary
Content-Type:application/octet-stream
Date:Mon, 21 Mar 2016 12:58:12 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=15, max=41
Pragma:no-cache
Server:Apache
Strict-Transport-Security:max-age=31556926
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Frame-Options:SAMEORIGIN
X-Powered-By:PHP/5.6.17
```

Webserver: Apache/2.2.15
PHP is 5.6.17, but we're using the suhosin extension which may also be the culprit of this. I don't know if it's worth the time to search any further, but it sure is coming from the server side. I also double-checked and saw that in index.php of monstaftp the header was really written. strange.

**Comment by greecemunky** [comment]
The good thing about digging deeper is that this issue/symptom may occur to someone else, and if/when that occurs we can advise what could be the cause and hopefully a workaround or fix.

This [SF thread](http://serverfault.com/questions/183843/content-length-not-sent-when-gzip-compression-enabled-in-apache) relating to a very similar issue suggests it's related to chunked data transfers (on Apache).  There's also a workaround function that may be worthwhile considering.

As per [Apache's mod_deflate page](http://httpd.apache.org/docs/current/mod/mod_deflate.html#deflatebuffersize), "If the compressed response size is bigger than the one specified by this directive [_DeflateBufferSize_] then httpd will switch to chunked encoding (HTTP header Transfer-Encoding set to Chunked), with the side effect of not setting any Content-Length HTTP header."

Do you have `AddOutputFilterByType DEFLATE <mimetype>`, where `application/octet-stream` and/or `application/download` are in the list of MIME types, set anywhere within your Apache config files or .htaccess overrides?  My Apache configuration covers text files (HTML, plain text, XML, JS, CSS - content that may not be compressed or minified).

If the answer to the above is yes, then it's probably best to remove them.  If the answer is no, it could be another Apache, PHP or Suhosin configuration setting, or a bug.

But your committed fix does fix the issue, for Monsta, however you may still experience similar issues with other self-hosted web apps.

**Pull request merged**
