### PR TITLE
Remove irrelevant headers used for HTTP downloads.

### PR DESCRIPTION
**Pull request by greecemunky**

### CODE REVIEW

**Comment by greecemunky** [comment]
References for changes:

http://stackoverflow.com/questions/2882472/php-send-file-to-user#comment13845155_2882523
http://stackoverflow.com/questions/7285372/is-content-transfer-encoding-an-http-header

`Content-Transfer-Encoding` is an email header, not a HTTP header
`Content-Type: application/download` is a duplicate header, potentially overriding the former **Content-Type: application/octet-stream** header (based on how PHP handles header requests)
`Content-Description` is an email header, not a HTTP header

That said, it is not a big issue.  But there's no point sending stuff that is useless and could possibly confuse a web browser.

I see examples using [PHP's rawfile() example](http://php.net/manual/en/function.readfile.php) verbatim, which is incorrect.  Attempts to have the example corrected have fallen on deaf ears (as per above link).

**Comment by MonstaApps** [comment]
Thanks for the changes. I'll merge the pull request once I've fixed another issue.

**Comment by greecemunky** [comment]
Thanks for that.

Also, apologies for "sneaking" the session stuff in.  That was to be in a separate pull request, not to be combined with this pull request (still getting my head around SmartGit and Git in general).

**Comment by MonstaApps** [comment]
Hah yeah I was trying to find the separate pull request ;-) All good, adding a session prefix was a good idea!

**Pull request merged**
